<?php
$z[0]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a>",124,210);
$z[0][4]['typeid']="1";
$z[1]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",228,361);
$z[1][4]['type']="son";
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",444,530);
$z[2][4]['typeid']="11";
$z[3]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",547,681);
$z[3][4]['type']="son";
$z[3][4]['typeid']="11";
$z[4]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",764,849);
$z[4][4]['typeid']="5";
$z[5]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",866,999);
$z[5][4]['type']="son";
$z[5][4]['typeid']="5";
$z[6]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1082,1167);
$z[6][4]['typeid']="8";
$z[7]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",1184,1317);
$z[7][4]['type']="son";
$z[7][4]['typeid']="8";
$z[8]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1400,1486);
$z[8][4]['typeid']="16";
$z[9]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",1503,1637);
$z[9][4]['type']="son";
$z[9][4]['typeid']="16";
$z[10]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1720,1806);
$z[10][4]['typeid']="19";
$z[11]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",1823,1957);
$z[11][4]['type']="son";
$z[11][4]['typeid']="19";
$z[12]=Array("global","",2246,2278);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",2357,2383);
$z[13][4]['name']="cfg_powerby";
$z[14]=Array("global","",2403,2427);
$z[14][4]['name']="cfg_beian";

?>