<?php
$z[0]=Array("global","",339,361);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("channelartlist","\r\n       <li class=\"nLi {dede:field.currentstyle/}\" ><!--<li class=\"nLi on\">-->\r\n        <h3><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h3>\r\n        <ul class=\"sub\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n    ",616,1073);
$z[1][4]['typeid']="top";
$z[1][4]['row']="6";
$z[1][4]['currentstyle']="on";
$z[2]=Array("global","",1133,1165);
$z[2][4]['name']="cfg_templets_skin";

?>